
services:
  web:
    command: npm run dev
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages/domain:/app/packages/domain
      - /app/apps/web/node_modules
      - /app/packages/domain/node_modules

  api:
    entrypoint:
      - sh
      - -c
      - node scripts/wait-for-db.mjs && npm run migration:run && npm run seed && npm run start:dev
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages/domain:/app/packages/domain
      - /app/apps/api/node_modules
      - /app/packages/domain/node_modules
